#!/bin/bash

# NeighborGigs Quick Connect to Supabase
# This script helps you get the credentials you need

echo "=========================================="
echo "   NeighborGigs Supabase Connection"
echo "=========================================="
echo ""
echo "Your Supabase Project:"
echo "  Project Ref: kxpglaetbawiugqmihfj"
echo "  API URL: https://kxpglaetbawiugqmihfj.supabase.co"
echo ""
echo "=========================================="
echo "   WHAT YOU NEED TO DO"
echo "=========================================="
echo ""
echo "1. Open Supabase Dashboard:"
echo "   https://supabase.com/dashboard/project/kxpglaetbawiugqmihfj"
echo ""
echo "2. Go to: Settings → API"
echo ""
echo "3. Copy these values:"
echo "   • Project URL (should be above)"
echo "   • anon public key (starts with eyJhb...)"
echo ""
echo "4. Go to: Settings → Database"
echo ""
echo "5. Find the Database Password (click 'Reveal' if needed)"
echo ""
echo "=========================================="
echo "   UPDATE YOUR ENV FILES"
echo "=========================================="
echo ""

PROJECT_URL="https://kxpglaetbawiugqmihfj.supabase.co"

echo "Add to mobile-app/.env.local:"
echo "EXPO_PUBLIC_SUPABASE_URL=$PROJECT_URL"
echo "EXPO_PUBLIC_SUPABASE_ANON_KEY=your-anon-key-here"
echo ""

echo "Add to neighborgigs-web/.env.local:"
echo "VITE_PUBLIC_SUPABASE_URL=$PROJECT_URL"
echo "VITE_PUBLIC_SUPABASE_ANON_KEY=your-anon-key-here"
echo ""

echo "Add to web-dashboard/.env.local:"
echo "NEXT_PUBLIC_SUPABASE_URL=$PROJECT_URL"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key-here"
echo ""

echo "=========================================="
echo "   DATABASE STATUS"
echo "=========================================="
echo ""
echo "Checking if tables exist..."
echo ""
echo "You can check this in Supabase Dashboard:"
echo "1. Go to: Table Editor"
echo "2. Look for tables: users, broadcasts, tasks, etc."
echo ""
echo "If tables don't exist, run the schema:"
echo "1. Go to: SQL Editor"
echo "2. Open: backend/supabase/schema.sql"
echo "3. Copy and paste the entire file"
echo "4. Click 'Run'"
echo ""
